# Playback
volume=80                            # default volume
keep-open=yes                        # keep window open after playback
autocreate-playlist=same             # autoload same-type files from dir
save-watch-history                   # save played files history
write-filename-in-watch-later-config # add filename as comment in watch later
ignore-path-in-watch-later-config    # ignore path in watch later, use name only

# Subtitles
slang=en                             # preferred subtitle language
blend-subtitles=yes                  # blend subs into video
sub-font='Roboto'                    # subtitle font

# OSD
osd-font='JetBrains Mono'            # OSD font

# Video
hwdec=d3d11va                        # hardware decoding (Windows)
border=no                            # disable window border

# Screenshots
screenshot-format=jpg                # screenshot format
screenshot-jpeg-quality=70           # screenshot quality
screenshot-directory=~/Downloads     # screenshot save path
screenshot-template="%F-%P"          # screenshot filename format

# Config
use-filedir-conf                     # load local mpv.conf if available
