# --- Hardware & Performance ---
profile=fast
hwdec=auto

# --- Window Layout ---
border=no
ontop=yes
autofit=40%x40%
geometry=100%:100%

# --- User Interface ---
osc=no
osd-bar=no
osd-font="Inter Display"

# --- Playback & Audio ---
volume=100
volume-max=200
keep-open=yes
use-filedir-conf

# --- Watch History ---
save-watch-history
write-filename-in-watch-later-config
ignore-path-in-watch-later-config

# --- Subtitles ---
slang=eng,en,unknown,any
blend-subtitles=yes
sub-font="Inter Display"
sub-font-size=45
sub-outline-size=2.4
#sub-fonts-dir=/storage/emulated/0/Android/media/is.xyz.mpv/fonts

# --- Screenshots ---
screenshot-format=jpg
screenshot-jpeg-quality=85
screenshot-directory=~/Downloads
screenshot-template="%F-%P"