seekbarfg_color=#00A8E1
seekbarbg_color=#999999

seek_handle_color=#FFFFFF
seek_handle_border_color=disable

volumebar_match_seek_color=yes

nibbles_style=triangle
nibble_color=#FFFFFF
nibble_current_color=#FEBD69

ab_loop_color=#005B82

hover_effect_color=#40C4FF